# Generated by Django 5.0.1 on 2026-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_synclog_progress_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.CharField(choices=[('classic', 'Classic'), ('casual', 'Casual')], default='classic', max_length=20, verbose_name='Коллекция'),
        ),
    ]
