# Generated by Django 5.0.1 on 2026-03-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_collection_favorite'),
        ('catalog', '0005_favorite'),
    ]

    operations = [
    ]
